### ISSUE TITLE
Atom Feed links point to wrong link

### ISSUE THREAD

**Issue by Lassulus** [brockman-news/brockman#16]
Seems like atom links are links from the text and not the links to the post itself

**Comment by kmein** [comment]
Could you give an example?

**Comment by Lassulus** [comment]
http://rss.r/?action=display&bridge=Telegram&username=haintz&format=Atom

**Comment by Lassulus** [comment]
not sure whats happening there, but sometimes an item generates multiple links and the link content changes (because of telegram CDN) and brockman thinks its new
