### ISSUE TITLE
URL shortening

### ISSUE THREAD

**Issue by Lassulus** [brockman-news/brockman#2]
sometimes the links to the news-sites are horribly long and therefore really hard to click inside a terminal window (if one uses weechat for example). So an option for an url-shortener would be cool. The link would be send there via a POST request and the result should be printed out then.

**Comment by Lassulus** [comment]
example with curl: `curl -d http://blog.fefe.de http://go.lassul.us`

**Comment by Lassulus** [comment]
whups, I posted a broken example. real one is:
`curl -Ss -F uri='http://blog.fefe.de' http://go.lassul.us`

**Comment by kmein** [comment]
Fixed in 1ab1890843a13af92484ac78d97ed6df3ce88476
